server:
    port: 8080

spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    dbcp2:
      driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/univ
    username: postgres
    password: 1234
    platform: postgres
    continue-on-error: true
  resources:
    static-locations: classpath:/resources/static/**, classpath:/META-INF/resources/
  data:
    mongodb:
      database: shop
      uri: mongodb://localhost:27017

    cassandra:
      port: 9042
      keyspace-name: sample

    neo4j:
      username: neo4j
      password: 1234

logging:
  level: error